-- settings.lua
-- Author: Francisco Cornejo-Garcia (franciscornejog)
-- Return a table of settings with predefined colors

local colors = require('noired.colors')

vim.g.terminal_color_0 = colors.dark0
vim.g.terminal_color_8 = colors.gray
vim.g.terminal_color_1 = colors.neutral_red
vim.g.terminal_color_9 = colors.bright_red
vim.g.terminal_color_2 = colors.neutral_green
vim.g.terminal_color_10 = colors.bright_green
vim.g.terminal_color_3 = colors.neutral_yellow
vim.g.terminal_color_11 = colors.bright_yellow
vim.g.terminal_color_4 = colors.neutral_blue
vim.g.terminal_color_12 = colors.bright_blue
vim.g.terminal_color_5 = colors.neutral_purple
vim.g.terminal_color_13 = colors.bright_purple
vim.g.terminal_color_6 = colors.neutral_aqua
vim.g.terminal_color_14 = colors.bright_aqua
vim.g.terminal_color_7 = colors.light4
vim.g.terminal_color_15 = colors.light1

local M = {
    Bold = { bold = true },
    Boolean = { fg = colors.bright_purple },
    Character = { fg = colors.bright_purple },
    ColorColumn = { bg = colors.dark1 },
    Comment = { fg = colors.gray, italic = true },
    Conceal = { fg = colors.bright_blue },
    Conditional = { fg = colors.bright_red },
    Constant = { fg = colors.bright_purple },
    Cursor = { reverse = true },
    CursorColumn = { bg = colors.dark1 },
    CursorIM = { reverse = true },
    CursorLine = { bg = colors.dark1 },
    CursorLineNr = { fg = colors.bright_yellow, bg = colors.dark1 },
    Debug = { fg = colors.bright_red },
    Define = { fg = colors.bright_aqua },
    Delimiter = { fg = colors.light3 },
    DiffAdd = { fg = colors.bright_green },
    DiffChange = { fg = colors.bright_aqua },
    DiffDelete = { fg = colors.bright_red },
    DiffText = { fg = colors.bright_yellow },
    Directory = { fg = colors.light0, bold = true },
    Error = { fg = colors.bright_red },
    ErrorMsg = { fg = colors.bright_red, bold = true },
    Exception =  { fg = colors.bright_red },
    Float = { fg = colors.bright_purple },
    FoldColumn = { fg = colors.gray },
    Folded = { fg = colors.gray, italic = true },
    Function = { fg = colors.bright_green, bold = true },
    Identifier = { fg = colors.bright_blue },
    Ignore = {},
    IncSearch = { fg = colors.dark0, bg = colors.bright_orange },
    Include = { fg = colors.bright_aqua },
    Italic = { italic = true },
    Keyword = { fg = colors.bright_red },
    Label = { fg = colors.bright_red },
    LineNr = { fg = colors.dark4 },
    Macro = { fg = colors.bright_aqua },
    MatchParen = { bg = colors.bright_orange, bold = true },
    ModeMsg = { fg = colors.bright_yellow, bold = true },
    MoreMsg = { fg = colors.bright_yellow, bold = true },
    NonText = { fg = colors.dark1 },
    Normal = { fg = colors.light1, bg = colors.dark0 },
    Number = { fg = colors.bright_purple },
    Operator = { fg = colors.light1 },
    Pmenu = { fg = colors.light1, bg = colors.dark0 },
    PmenuSbar = { bg = colors.dark0 },
    PmenuSel = { fg = colors.bright_orange, bold = true },
    PmenuThumb = { bg = colors.bright_orange },
    PreCondit = { fg = colors.bright_aqua },
    PreProc = { fg = colors.bright_aqua },
    Question = { fg = colors.bright_orange, bold = true },
    QuickFixLine = { bg = colors.dark0, bold = true },
    Repeat = { fg = colors.bright_red },
    Search = { fg = colors.bright_yellow },
    SignColumn = { bg = colors.dark0 },
    SignatureMarkText = { fg = colors.bright_blue, bg = colors.dark1, reverse = true },
    SignatureMarkerText = { fg = colors.bright_purple, bg = colors.dark1, reverse = true },
    Special = { fg = colors.bright_orange },
    SpecialChar = { fg = colors.bright_red },
    SpecialComment = { fg = colors.light0 },
    SpecialKey = { fg = colors.light4 },
    SpellBad = { undercurl = true, sp = colors.bright_red },
    SpellCap = { fg = colors.bright_blue, bold = true, italic = true },
    SpellLocal = { undercurl = true, sp = colors.bright_aqua },
    SpellRare = { undercurl = true, sp = colors.bright_purple },
    Statement = { fg = colors.bright_red },
    StatusLine = { fg = colors.light1 },
    StatusLineNC = { fg = colors.light2 },
    StorageClass = { fg = colors.bright_orange },
    String = { fg = colors.bright_purple },
    Structure = { fg = colors.bright_aqua },
    TSAnnotation = { fg = colors.bright_aqua },
    TSAttribute = { fg = colors.bright_aqua },
    TSBoolean = { fg = colors.bright_purple },
    TSCharacter = { fg = colors.bright_purple },
    TSComment = { fg = colors.gray, italic = true },
    TSConditional = { fg = colors.bright_red },
    TSConstBuiltin = { fg = colors.bright_orange },
    TSConstMacro = { fg = colors.bright_aqua },
    TSConstant = { fg = colors.bright_purple },
    TSConstructor = { fg = colors.bright_orange },
    TSEmphasis = { italic = true },
    TSError = {},
    TSException = { fg = colors.bright_red },
    TSField = { fg = colors.bright_blue },
    TSFloat = { fg = colors.bright_purple },
    TSFuncBuiltin = { fg = colors.bright_orange, italic = true },
    TSFuncMacro = { fg = colors.bright_aqua },
    TSFunction = { fg = colors.bright_green, bold = true },
    TSInclude = { fg = colors.bright_aqua },
    TSKeyword = { fg = colors.bright_red },
    TSKeywordFunction = { fg = colors.bright_red },
    TSKeywordOperator = { fg = colors.bright_red },
    TSLabel = { fg = colors.bright_red },
    TSLiteral = { fg = colors.bright_purple },
    TSMethod = { fg = colors.bright_green, bold = true },
    TSNamespace = { fg = colors.bright_aqua },
    TSNone = {},
    TSNumber = { fg = colors.bright_purple },
    TSOperator = { fg = colors.light1 },
    TSParameter = { fg = colors.bright_blue },
    TSParameterReference = { fg = colors.bright_blue },
    TSProperty = { fg = colors.bright_blue },
    TSPunctBracket = { fg = colors.light3 },
    TSPunctDelimiter = { fg = colors.light3 },
    TSPunctSpecial = { fg = colors.light3 },
    TSRepeat = { fg = colors.bright_red },
    TSString = { fg = colors.bright_purple },
    TSStringEscape = { fg = colors.bright_red },
    TSStringRegex = { fg = colors.bright_purple },
    TSStrong = { bold = true },
    TSStructure = { fg = colors.bright_orange },
    TSTag = { fg = colors.bright_orange },
    TSTagDelimiter = { fg = colors.bright_green },
    TSText = {},
    TSTitle = { fg = colors.bright_green, bold = true },
    TSType = { fg = colors.bright_yellow },
    TSTypeBuiltin = { fg = colors.bright_yellow },
    TSURI = { fg = colors.bright_blue, underline = true },
    TSUnderline = { underline = true },
    TSVariable = { fg = colors.light1 },
    TSVariableBuiltin = { fg = colors.bright_orange, italic = true },
    TabLine = { fg = colors.dark4, bg = colors.dark1, reverse = true },
    TabLineFill = { fg = colors.dark4, bg = colors.dark1, reverse = true },
    TabLineSel = { fg = colors.bright_green, bg = colors.dark1, reverse = true },
    Tag = { fg = colors.bright_aqua, bold = true },
    TelescopeBorder = { fg = colors.light1 },
    TelescopeMatching = { fg = colors.bright_blue },
    TelescopeMultiSelection = { fg = colors.gray },
    TelescopeNormal = { fg = colors.light1 },
    TelescopePreviewBorder = { fg = colors.light1 },
    TelescopePrompt = { fg = colors.light1 },
    TelescopePromptBorder = { fg = colors.light1 },
    TelescopePromptPrefix = { fg = colors.bright_red },
    TelescopeResultsBorder = { fg = colors.light1 },
    TelescopeSelection = { fg = colors.bright_orange, bold = true },
    TelescopeSlectionCaret = { fg = colors.bright_red },
    Todo = { fg = colors.light0, bold = true, italic = true },
    Type = { fg = colors.bright_yellow },
    Typedef = { fg = colors.bright_yellow },
    Underlined = { fg = colors.bright_blue, underline = true },
    VertSplit = { bg = colors.dark0 },
    Visual = { bg = colors.dark3 },
    VisualNOS = { bg = colors.dark3 },
    WarningMsg = { fg = colors.bright_red, bold = true },
    WildMenu = { fg = colors.bright_blue, bg = colors.dark2, bold = true },
    diffAdded = { fg = colors.bright_green },
    diffChanged = { fg = colors.bright_aqua },
    diffFile = { fg = colors.bright_orange },
    diffLine = { fg = colors.bright_blue },
    diffNewFile = { fg = colors.bright_yellow },
    diffRemoved = { fg = colors.bright_red },
    gitcommitDiscardedFile = { fg = colors.bright_red },
    gitcommitSelectedFile = { fg = colors.bright_green },
    healthError = { fg = colors.dark0, bg = colors.bright_red },
    healthSuccess = { fg = colors.dark0, bg = colors.bright_green },
    healthWarning = { fg = colors.dark0, bg = colors.bright_yellow },
    helpHyperTextEntry = { fg = colors.red },
    iCursor = { reverse = true },
    iitle = { fg = colors.bright_green, bold = true },
    lCursor = { reverse = true },
    netrwClassify = { fg = colors.aqua },
    netrwCmdSep = { fg = colors.light3 },
    netrwComment = { fg = colors.gray },
    netrwDir = { fg = colors.bright_orange },
    netrwExe = { fg = colors.light0 },
    netrwHelpCmd = { fg = colors.light0 },
    netrwLink = { fg = colors.gray },
    netrwList = { fg = colors.blue },
    netrwSymLink = { fg = colors.bright_yellow },
    netrwVersion = { fg = colors.green },
    vCursor = { reverse = true },
    GitSignsAdd = { fg = colors.bright_green },
    GitSignsChange = { fg = colors.bright_aqua },
    GitSignsDelete = { fg = colors.bright_red },
    GitSignsCurrentLineBlame = { fg = colors.dark1 },
}

    --[[ lspsaga.nvim
    LspSagaDiagnosticBorder = base.NormalNC,
    LspSagaDiagnosticHeader = base.GruvboxRed,
    LspSagaDiagnosticTruncateLine = base.NormalNC,
    LspFloatWinBorder = base.NormalNC,
    LspSagaBorderTitle = base.Title,
    TargetWord = base.Error,
    ReferencesCount = base.Title,
    ReferencesIcon = { fg = colors.bright_orange, italic = true },
    DefinitionCount = base.Title,
    TargetFileName = base.Comment,
    DefinitionIcon = { fg = colors.bright_orange, italic = true },
    ProviderTruncateLine = base.NormalNC,
    SagaShadow = base.GruvboxBg0,
    LspSagaFinderSelection = base.Search,
    DiagnosticTruncateLine = base.NormalNC,
    DiagnosticWarning = base.DiagnosticWarn,
    DiagnosticInformation = base.DiagnosticInfo,
    DefinitionPreviewTitle = base.Title,
    LspSagaShTruncateLine = base.NormalNC,
    LspSagaDocTruncateLine = base.NormalNC,
    LineDiagTuncateLine = base.NormalNC,
    LspSagaCodeActionTitle = base.Title,
    LspSagaCodeActionTruncateLine = base.NormalNC,
    LspSagaCodeActionContent = base.Normal,
    LspSagaRenamePromptPrefix = base.GruvboxFg2,
    LspSagaRenameBorder = { gui = styles.bold },
    LspSagaHoverBorder = { gui = styles.bold },
    LspSagaSignatureHelpBorder = { gui = styles.bold },
    LspSagaCodeActionBorder = { gui = styles.bold },
    LspSagaAutoPreview = {},
    LspSagaDefPreviewBorder = { gui = styles.bold },
    LspLinesDiagBorder = { gui = styles.bold },

    -- vim-startify
    StartifyBracket = base.GruvboxFg3,
    StartifyFile = base.GruvboxFg1,
    StartifyNumber = base.GruvboxBlue,
    StartifyPath = base.GruvboxGray,
    StartifySlash = base.GruvboxGray,
    StartifySection = base.GruvboxYellow,
    StartifySpecial = base.GruvboxBg2,
    StartifyHeader = base.GruvboxOrange,
    StartifyFooter = base.GruvboxBg2,
    StartifyVar = "StartifyPath",
    StartifySelect = base.Title,

    -- vim-signify
    SignifySignAdd = base.GruvboxGreenSign,
    SignifySignChange = base.GruvboxAquaSign,
    SignifySignDelete = base.GruvboxRedSign,

    -- syntastic
    SyntasticError = base.GruvboxRedUnderline,
    SyntasticWarning = base.GruvboxYellowUnderline,
    SyntasticErrorSign = base.GruvboxRedSign,
    SyntasticWarningSign = base.GruvboxYellowSign,

    -- termdebug
    debugPC = { bg = colors.faded_blue },
    debugBreakpoint = base.GruvboxRedSign,

    -- vim-dirvish
    DirvishPathTail = base.GruvboxAqua,
    DirvishArg = base.GruvboxYellow,

    -- nerdtree
    NERDTreeDir = base.GruvboxAqua,
    NERDTreeDirSlash = base.GruvboxAqua,
    NERDTreeOpenable = base.GruvboxOrange,
    NERDTreeClosable = base.GruvboxOrange,
    NERDTreeFile = base.GruvboxFg1,
    NERDTreeExecFile = base.GruvboxYellow,
    NERDTreeUp = base.GruvboxGray,
    NERDTreeCWD = base.GruvboxGreen,
    NERDTreeHelp = base.GruvboxFg1,
    NERDTreeToggleOn = base.GruvboxGreen,
    NERDTreeToggleOff = base.GruvboxRed,

    -- coc.nvim
    CocErrorSign = base.GruvboxRedSign,
    CocWarningSign = base.GruvboxOrangeSign,
    CocInfoSign = base.GruvboxBlueSign,
    CocHintSign = base.GruvboxAquaSign,
    CocErrorFloat = base.GruvboxRed,
    CocWarningFloat = base.GruvboxOrange,
    CocInfoFloat = base.GruvboxBlue,
    CocHintFloat = base.GruvboxAqua,
    CocDiagnosticsError = base.GruvboxRed,
    CocDiagnosticsWarning = base.GruvboxOrange,
    CocDiagnosticsInfo = base.GruvboxBlue,
    CocDiagnosticsHint = base.GruvboxAqua,
    CocSelectedText = base.GruvboxRed,
    CocCodeLens = base.GruvboxGray,
    CocErrorHighlight = base.GruvboxRedUnderline,
    CocWarningHighlight = base.GruvboxOrangeUnderline,
    CocInfoHighlight = base.GruvboxBlueUnderline,
    CocHintHighlight = base.GruvboxAquaUnderline,

    -- ale.vim
    ALEError = base.GruvboxRedUnderline,
    ALEWarning = base.GruvboxYellowUnderline,
    ALEInfo = base.GruvboxBlueUnderline,
    ALEErrorSign = base.GruvboxRedSign,
    ALEWarningSign = base.GruvboxYellowSign,
    ALEInfoSign = base.GruvboxBlueSign,
    ALEVirtualTextError = base.GruvboxRed,
    ALEVirtualTextWarning = base.GruvboxYellow,
    ALEVirtualTextInfo = base.GruvboxBlue,
    -- vim-buftabline
    BufTabLineCurrent = base.TabLineSel,
    BufTabLineActive = base.PmenuSel,
    BufTabLineHidden = base.TabLine,
    BufTabLineFill = base.TabLineFill,
    BufTabLineModifiedCurrent = "BufTabLineCurrent",
    BufTabLineModifiedActive = "BufTabLineActive",
    BufTabLineModifiedHidden = "BufTabLineHidden",

    -- ctrlP
    CtrlPMatch = base.Identifier,
    CtrlPNoEntries = base.Error,
    CtrlPPrtBase = base.Comment,
    CtrlPPrtCursor = base.Constant,
    CtrlPLinePre = { fg = base.GruvboxBg2.fg },
    CtrlPMode1 = base.Character,
    CtrlPMode2 = base.LineNr,
    CtrlPStats = base.Function,

    -- fzf.vim
    Fzf1 = { fg = base.GruvboxBlue.fg, bg = base.GruvboxBg1.fg },
    Fzf2 = { fg = base.GruvboxOrange.fg, bg = base.GruvboxBg1.fg },
    Fzf3 = { fg = base.GruvboxFg4.fg, bg = base.GruvboxBg1.fg },
    ShowMarksHLl = base.GruvboxBlueSign,
    ShowMarksHLu = base.GruvboxBlueSign,
    ShowMarksHLo = base.GruvboxBlueSign,
    ShowMarksHLm = base.GruvboxBlueSign,

    -- git-gutter
    GitGutterAdd = base.GruvboxGreenSign,
    GitGutterChange = base.GruvboxAquaSign,
    GitGutterDelete = base.GruvboxRedSign,
    GitGutterChangeDelete = base.GruvboxAquaSign,

    -- nvim-cmp
    CmpItemAbbr = base.GruvboxFg0,
    CmpItemAbbrDeprecated = base.GruvboxFg0,
    CmpItemAbbrMatch = base.GruvboxBlue,
    CmpItemAbbrMatchFuzzy = { gui = styles.underline, fg = base.GruvboxAqua.fg },
    CmpItemKind = base.GruvboxOrange,
    CmpItemKindClass = base.GruvboxGreen,
    CmpItemKindConstructor = base.GruvboxGreen,
    CmpItemKindField = base.GruvboxAqua,
    CmpItemKindFile = base.GruvboxOrange,
    CmpItemKindFolder = base.GruvboxOrange,
    CmpItemKindFunction = base.GruvboxPurple,
    CmpItemKindInterface = base.GruvboxGreen,
    CmpItemKindKeyword = base.Keyword,
    CmpItemKindMethod = base.GruvboxPurple,
    CmpItemKindSnippet = base.GruvboxYellow,
    CmpItemKindText = base.GruvboxFg0,
    CmpItemKindValue = base.GruvboxOrange,
    CmpItemKindVariable = base.GruvboxBlue,
    CmpItemMenu = base.GruvboxGray,

    -- LSP
    LspCodeLens = base.GruvboxGray,
    LspReferenceRead = { bg = base.GruvboxBg2.fg, gui = styles.underline },
    LspReferenceText = { bg = base.GruvboxBg2.fg, gui = styles.underline },
    LspReferenceWrite = { bg = base.GruvboxBg2.fg, gui = styles.underline },

    -- Diagnostic
    DiagnosticError = base.GruvboxRed,
    DiagnosticSignError = base.GruvboxRedSign,
    DiagnosticUnderlineError = base.GruvboxRedUnderline,
    DiagnosticWarn = base.GruvboxYellow,
    DiagnosticSignWarn = base.GruvboxYellowSign,
    DiagnosticUnderlineWarn = base.GruvboxYellowUnderline,
    DiagnosticInfo = base.GruvboxBlue,
    DiagnosticSignInfo = base.GruvboxBlueSign,
    DiagnosticUnderlineInfo = base.GruvboxBlueUnderline,
    DiagnosticHint = base.GruvboxAqua,
    DiagnosticSignHint = base.GruvboxAquaSign,
    DiagnosticUnderlineHint = base.GruvboxAquaUnderline,
    DiagnosticFloatingError = base.GruvboxRed,
    DiagnosticFloatingWarn = base.GruvboxOrange,
    DiagnosticFloatingInfo = base.GruvboxBlue,
    DiagnosticFloatingHint = base.GruvboxAqua,
    DiagnosticVirtualTextError = base.GruvboxRed,
    DiagnosticVirtualTextWarn = base.GruvboxYellow,
    DiagnosticVirtualTextInfo = base.GruvboxBlue,
    DiagnosticVirtualTextHint = base.GruvboxAqua,

    -- mail.vim
    mailQuoted1 = base.GruvboxAqua,
    mailQuoted2 = base.GruvboxPurple,
    mailQuoted3 = base.GruvboxYellow,
    mailQuoted4 = base.GruvboxGreen,
    mailQuoted5 = base.GruvboxRed,
    mailQuoted6 = base.GruvboxOrange,
    mailSignature = base.Comment,
    --]]

return M
